version: "3.x"

networks:
  docker-practice-net:
    driver: bridge

services:
  java-backend:
    build: 
      context: images/java-backend
    container_name: java-backend
    restart: always
    volumes:
      - type: bind  
        source: ../../target
        target: /java-backend
    working_dir: /java-backend
    networks:     
      - docker-practice-net
    ports:
      - 8888:8080
    depends_on:
      - pg
      - redis
    entrypoint: ["java", "-jar", "docker-practice-java-0.0.1-SNAPSHOT.jar"]

  pg:
    image: postgres:alpine
    container_name: pg
    restart: always
    volumes:
      # Надо подняться из директорий ops-tools/docker в 
      # корневую директорию проекта (кажется, что это далеко
      # не идеальный вариант (или нормально?))
      - "../../data/postgres:/var/lib/postgresql/data"
      - "../../data/dump:/db-dump"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
    networks:     
      - docker-practice-net
    ports: 
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:     
      - docker-practice-net
    ports: 
      - 6379:6379
