version: "3.x"

services:
  java-backend:
    image: eclipse-temurin:17-alpine
    networks:     
      - docker-practice-net
    ports:
      - "8080:8080"
    depends_on:
      - pg
      - redis

  pg:
    image: postgres:alpine
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      # Наверное, так должен быть сделан пункт g
      - "./data/dump:/db-dump"
    environment:
      - POSTGRES_DB=school 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=school
    networks:     
      - docker-practice-net
    ports: 
      - "5432:5432"

  redis:
    image: redis:alpine
    networks:     
      - docker-practice-net
    ports: 
      - "6379:6379"

networks:
  docker-practice-net:
    driver: bridge
