version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
      PGDATA: /data/postgres
    volumes:
      - /data/postgres:/var/lib/postgresql/data
      - /db-dump:/data/dump
    ports:
      - "5432:5432"
    networks:
      - docker-practice-net
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/var/lib/redis/data

  app:
    build:
      context: .
      dockerfile: ./images/app/Dockerfile
    ports:
      - "8888:8888"
    environment:
      POSTGRES_HOST: 6379
      REDIS_HOST: 5432
    restart: always
    links:
      - postgres
      - redis

networks:
  docker-practice-net:


